export const Privileges = {
  // VIEW_DASHBOARD: "VIEW.DASHBOARD",
  VIEW_DASHBOARD: "VIEW.REGISTRATION",
  VIEW_REGISTRATION: "VIEW.REGISTRATION",
  VIEW_COMPANIES: "VIEW.COMPANIES",
  VIEW_PAYMENTS: "VIEW.PAYMENTS",
  VIEW_QR_CODES: "VIEW.QR_CODES",
  VIEW_REPORTS: "VIEW.REPORTS",
  VIEW_SETTINGS: "VIEW.SETTINGS",
  VIEW_SETTINGS_ROLES: "VIEW.SETTINGS.ROLES",
  VIEW_SETTINGS_USER: "VIEW.SETTINGS.USER",
};

export default Privileges;
